#All ${..} are coming from .env file, this should only exist in production ready containers
version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    command: ['npm', 'start']
    depends_on: 
      - api
    environment:
      # we set our environment variables in the container app
      PORT: ${WEB_CONTAINER_PORT}
    ports:
      - ${WEB_PORT}:${WEB_CONTAINER_PORT}
    restart: always
    volumes:
      - ./:/usr/src/app
  
  api:
    build: ./api
    container_name: api
    command: ['npm', 'start']
    environment:
      # we set our environment variables in the container app
      PORT: ${API_CONTAINER_PORT}
      MONGO_DB_URI: mongodb+srv://${MONGO_USER}:${MONGO_PSW}@cluster0.lhauy.mongodb.net/chat-app
    ports:
      - ${API_PORT}:${API_CONTAINER_PORT}
    restart: always
    volumes:
      - ./:/usr/src/app